services:
  db:
    image: postgres:15
    container_name: dermacor
    restart: unless-stopped
    environment:
      POSTGRES_USER: dermacor
      POSTGRES_PASSWORD: dermacor
      POSTGRES_DB: dermacor
      TZ: America/Argentina/Buenos_Aires
      PGTZ: America/Argentina/Buenos_Aires
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: